#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# This is done because the user model is customized
python3 manage.py makemigrations
#
python3 manage.py migrate
python3 manage.py collectstatic --no-input
python3 manage.py runserver_plus 0.0.0.0:8000
