#!/bin/bash

# -A, --app <app>
# -b, --broker <broker>
# --result-backend <result_backend>
# --loader <loader>
# --config <config>
# --workdir <workdir>
# -C, --no-color¶
# -q, --quiet
# --version

set -o errexit
set -o nounset

worker_ready(){
   celery -A core.celery_app inspect ping
}

until worker_ready; do
   >&2 echo "Celery workers are not available .... :-( "
   sleep 1
done
>&2 echo "Celery workers are available and ready! .... :-)"

celery \
    -A core.celery_app \
    -b "${CELERY_BROKER_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
